kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: hello-node
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hello-node
    spec:
      restartPolicy: Always
      containers:
      - name: hello-node
        image: gcr.io/zero-downtime-test-1322/hello-node:v10
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          timeoutSeconds: 1
