kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      restartPolicy: Always
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-configmap-v7
          items:
          - key: hello-node
            path: hello-node.conf
      containers:
      - name: nginx
        image: nginx:1.10
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
